"""Conversational Streamlit entrypoint for the Solar Project RAG app."""

from __future__ import annotations

from typing import Any, Dict

import pandas as pd
import streamlit as st

from rag import SolarRAG


APP_BUILD = "2026-07-25-conversational-rag"

SUGGESTIONS = {
    ":blue[:material/partly_cloudy_day:] Riyadh weather": (
        "What was the weather in Riyadh on 2024-02-02?"
    ),
    ":orange[:material/solar_power:] Jeddah solar energy": (
        "How much solar energy could I get in Jeddah on 2024-06-15?"
    ),
    ":green[:material/check_circle:] Medina suitability": (
        "Was Medina suitable for solar generation on 2024-09-01?"
    ),
    ":violet[:material/air:] Dammam combined analysis": (
        "How were the weather, air quality, and solar potential in Dammam "
        "on 2024-03-10?"
    ),
}

WEATHER_FEATURES = {
    "temperature_2m_mean": ("Mean temperature", "°C"),
    "relative_humidity_2m_mean": ("Relative humidity", "%"),
    "wind_speed_10m_mean": ("Wind speed", "km/h"),
    "cloud_cover_mean": ("Cloud cover", "%"),
    "precipitation_sum": ("Precipitation", "mm"),
    "shortwave_radiation_sum": ("Shortwave radiation", "MJ/m²"),
    "sunshine_duration": ("Sunshine duration", "seconds"),
}

AIR_FEATURES = {
    "pm10": ("PM10", "µg/m³"),
    "pm2_5": ("PM2.5", "µg/m³"),
    "carbon_monoxide": ("Carbon monoxide", "µg/m³"),
    "nitrogen_dioxide": ("Nitrogen dioxide", "µg/m³"),
    "ozone": ("Ozone", "µg/m³"),
    "sulphur_dioxide": ("Sulphur dioxide", "µg/m³"),
}


st.set_page_config(
    page_title="Solar RAG assistant",
    page_icon="☀️",
    layout="wide",
    initial_sidebar_state="expanded",
)


def get_secret(name: str, default: str = "") -> str:
    """Read a root-level Streamlit secret without exposing it in the UI."""
    try:
        value = st.secrets.get(name, default)
    except Exception:
        value = default
    return str(value).strip()


@st.cache_resource(show_spinner=False)
def initialize_rag(
    ollama_api_key: str,
    ollama_host: str,
    ollama_model: str,
) -> SolarRAG:
    """Load the dataset once and rebuild the resource when configuration changes."""
    system = SolarRAG(
        ollama_api_key=ollama_api_key,
        ollama_host=ollama_host,
        ollama_model=ollama_model,
    )
    system.setup()
    return system


ollama_api_key = get_secret("OLLAMA_API_KEY")
ollama_host = get_secret("OLLAMA_HOST", "https://ollama.com")
ollama_model = get_secret("OLLAMA_MODEL", "gpt-oss:20b")

try:
    rag = initialize_rag(ollama_api_key, ollama_host, ollama_model)
except Exception as exc:
    st.error("The app could not load its dataset.")
    st.code(str(exc))
    st.info(
        "Make sure data/solar_dataset.csv or data/solar_dataset.csv.gz "
        "is committed to the GitHub repository."
    )
    st.stop()


st.session_state.setdefault("messages", [])


def format_measurement(value: Any, unit: str) -> str:
    """Format a numeric measurement for the result tables."""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    precision = 0 if unit in {"%", "seconds"} else 1
    return f"{number:.{precision}f} {unit}".strip()


def measurement_table(data: Dict, features: Dict[str, tuple[str, str]]) -> pd.DataFrame:
    """Build a display-safe table from selected retrieved features."""
    rows = []
    for key, (label, unit) in features.items():
        if data.get(key) is not None:
            rows.append(
                {
                    "Measurement": label,
                    "Observed value": format_measurement(data[key], unit),
                }
            )
    return pd.DataFrame(rows)


def render_analysis(result: Dict) -> None:
    """Render one complete RAG answer inside an assistant chat message."""
    if result.get("status") != "success":
        st.error(result.get("error", "The question could not be processed."))
        st.caption(
            "Include one supported city and a historical date, such as "
            "`Riyadh 2024-02-02`."
        )
        return

    predictions = result["predictions"]
    data = result["data"]
    llm_status = result.get("llm_status")

    st.markdown("#### Ollama RAG explanation")
    if llm_status == "ollama_cloud":
        st.caption(
            f":material/smart_toy: Generated by Ollama Cloud "
            f"(`{ollama_model}`) from retrieved data, ML predictions, and knowledge."
        )
    elif llm_status == "not_configured":
        st.warning(
            "Ollama Cloud is not configured. Showing the built-in grounded RAG "
            "summary instead."
        )
    else:
        st.warning(
            "Ollama Cloud could not generate this answer. Showing the built-in "
            "grounded RAG summary instead."
        )
        if result.get("llm_error"):
            st.caption(result["llm_error"])

    st.markdown(result["llm_response"])

    st.markdown("#### Model results")
    with st.container(horizontal=True):
        st.metric(
            "Estimated daily solar energy",
            f"{predictions['solar_output_kwh']:.1f} kWh",
            border=True,
        )
        st.metric(
            "Predicted AQI",
            f"{predictions['aqi_value']:.0f}",
            border=True,
        )
        st.metric(
            "Air-quality risk",
            predictions["aqi_risk_level"],
            border=True,
        )

    weather_column, air_column = st.columns(2)
    with weather_column:
        with st.container(border=True):
            st.markdown("**Retrieved weather features**")
            st.dataframe(
                measurement_table(data, WEATHER_FEATURES),
                hide_index=True,
                width="stretch",
            )

    with air_column:
        with st.container(border=True):
            st.markdown("**Retrieved air-quality features**")
            st.dataframe(
                measurement_table(data, AIR_FEATURES),
                hide_index=True,
                width="stretch",
            )

    with st.expander("Knowledge retrieved for this answer"):
        for item in result["interpretations"]:
            st.markdown(f"- {item}")

    with st.expander("How this answer was produced"):
        st.markdown(
            "1. The question parser identifies the city, date, and requested topics.\n"
            "2. The app retrieves that city-day's historical weather and pollution "
            "features from the project dataset.\n"
            "3. The trained models estimate daily solar output and AQI.\n"
            "4. TF-IDF retrieval selects relevant solar and air-quality knowledge.\n"
            "5. Ollama Cloud receives only that grounded context and writes the final "
            "explanation."
        )
        st.caption(
            "The dataset covers historical 2024 observations. Results are analytical "
            "estimates, not a live weather forecast or a guaranteed PV system yield."
        )


st.title("Solar RAG assistant")
st.caption(
    "Ask about historical weather, solar-energy potential, air quality, or solar "
    "suitability across Riyadh, Jeddah, Mecca, Medina, and Dammam."
)

with st.sidebar:
    st.header("System status")
    if rag.explainer.configured:
        st.success(f"Ollama Cloud configured\n\nModel: `{rag.explainer.model}`")
    else:
        st.warning("Ollama Cloud API key is not configured.")

    st.markdown("**Available data**")
    st.write(f"{rag.data_loader.min_date} to {rag.data_loader.max_date}")
    st.write(", ".join(rag.data_loader.cities))

    st.markdown("**Supported questions**")
    st.caption(
        "Weather conditions · estimated solar energy · air quality · "
        "solar suitability · combined analysis"
    )

    if st.button(
        "Clear conversation",
        icon=":material/delete_sweep:",
        width="stretch",
        disabled=not st.session_state.messages,
    ):
        st.session_state.messages = []
        st.rerun()

    st.caption(f"Build: {APP_BUILD}")


for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            st.markdown(message["content"])
        else:
            render_analysis(message["result"])


selected_suggestion = None
if not st.session_state.messages:
    st.info(
        "Ask a natural-language question that includes a supported city and a "
        "date from 2024."
    )
    selected_suggestion = st.pills(
        "Try asking",
        list(SUGGESTIONS),
        selection_mode="single",
        label_visibility="collapsed",
    )


prompt = st.chat_input(
    "Ask about weather, solar energy, air quality, or site suitability…",
    submit_mode="disable",
)
if selected_suggestion:
    prompt = SUGGESTIONS[selected_suggestion]


if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner(
            "Retrieving conditions, running the prediction models, and asking Ollama…"
        ):
            result = rag.process_query(prompt)
        render_analysis(result)

    st.session_state.messages.append({"role": "assistant", "result": result})
